In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from keras.models import Sequential
from keras.layers import Dense, Input
from keras.utils import to_categorical
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
df_dados = pd.read_csv('Clientes e Emprego2.csv')
df_dados.head()

,IDCREDITO,Duracao,HistoricoCredito,Proposito,Valor,Investimentos,Emprego,TempoParcelamento,EstadoCivil,FiadorTerceiros,...,Status,proposta,financiamentos,profissao,emprego,histcredito,fiador,residencia,estadocivil,investimentos
0,107,18,5,4,6458,2,2.0,2,4,3,...,0,veiculo novo,banco,altamente qualificado/empresario,>=7,todos pagos,nao,proria,Viuvo,<100\\n
1,108,12,2,4,6078,2,4.0,2,4,3,...,1,veiculo novo,nenhum,qualificado,4<=X<7,existentes/pagos,nao,proria,Viuvo,<100\\n
2,109,24,2,3,7721,1,1.0,1,1,3,...,1,moveis,nenhum,qualificado,<1,existentes/pagos,nao,proria,Solteiro,Desconhecido\\n
3,110,14,2,6,1410,3,2.0,1,3,3,...,1,abrir negocio,nenhum,qualificado,>=7,existentes/pagos,nao,proria,Divorciado,500<=X<1000
4,78,11,3,1,4771,2,NaN,2,4,3,...,1,reforma,nenhum,qualificado,NaN,Atrasos anteriores,nao,proria,Viuvo,<100\\n

In [3]:
# Excluindo colunas "desnecessárias ou substituídas.

df_dados.drop(columns = ['IDCREDITO', 'fiador', 'residencia', 'estadocivil', 'HistoricoCredito','Proposito', 'Investimentos', 'Emprego', 'EstadoCivil', 'FiadorTerceiros', 'ResidenciaDesde',
                      'OutrosFinanciamentos', 'Habitacao', 'EmprestimoExistente', 'Profissao', 'Dependentes', 'SocioEmpresa','TempoParcelamento'],
                        inplace = True)
df_dados.head()

,Duracao,Valor,Idade,Status,proposta,financiamentos,profissao,emprego,histcredito,investimentos
0,18,6458,39,0,veiculo novo,banco,altamente qualificado/empresario,>=7,todos pagos,<100\\n
1,12,6078,32,1,veiculo novo,nenhum,qualificado,4<=X<7,existentes/pagos,<100\\n
2,24,7721,30,1,moveis,nenhum,qualificado,<1,existentes/pagos,Desconhecido\\n
3,14,1410,35,1,abrir negocio,nenhum,qualificado,>=7,existentes/pagos,500<=X<1000
4,11,4771,51,1,reforma,nenhum,qualificado,NaN,Atrasos anteriores,<100\\n

In [4]:
# Colocando a coluna alvo no final.

df_dados['Status'] = df_dados.pop('Status')
df_dados.head()

,Duracao,Valor,Idade,proposta,financiamentos,profissao,emprego,histcredito,investimentos,Status
0,18,6458,39,veiculo novo,banco,altamente qualificado/empresario,>=7,todos pagos,<100\\n,0
1,12,6078,32,veiculo novo,nenhum,qualificado,4<=X<7,existentes/pagos,<100\\n,1
2,24,7721,30,moveis,nenhum,qualificado,<1,existentes/pagos,Desconhecido\\n,1
3,14,1410,35,abrir negocio,nenhum,qualificado,>=7,existentes/pagos,500<=X<1000,1
4,11,4771,51,reforma,nenhum,qualificado,NaN,Atrasos anteriores,<100\\n,1

In [5]:
df_dados.columns = ['Duracao', 'Valor', 'Idade', 'Proposta', 'Financiamentos', 'Profissao', 'Emprego', 'Historico_Credito', 'Investimentos','Status']
df_dados

,Duracao,Valor,Idade,Proposta,Financiamentos,Profissao,Emprego,Historico_Credito,Investimentos,Status
0,18,6458,39,veiculo novo,banco,altamente qualificado/empresario,>=7,todos pagos,<100\\n,0
1,12,6078,32,veiculo novo,nenhum,qualificado,4<=X<7,existentes/pagos,<100\\n,1
2,24,7721,30,moveis,nenhum,qualificado,<1,existentes/pagos,Desconhecido\\n,1
3,14,1410,35,abrir negocio,nenhum,qualificado,>=7,existentes/pagos,500<=X<1000,1
4,11,4771,51,reforma,nenhum,qualificado,NaN,Atrasos anteriores,<100\\n,1
...,...,...,...,...,...,...,...,...,...,...
995,15,1403,28,veiculo novo,nenhum,qualificado,1<=X<4,existentes/pagos,<100\\n,1
996,18,4297,40,moveis,nenhum,altamente qualificado/empresario,>=7,Atrasos anteriores,<100\\n,0
997,36,1977,40,educacao,nenhum,altamente qualificado/empresario,>=7,existentes/pagos,Desconhecido\\n,0
998,9,1136,32,educacao,nenhum,qualificado,>=7,Critico-outros creditos,>=1000,0
999,12,684,40,educacao,nenhum,nao qualificado,1<=X<4,existentes/pagos,<100\\n,0

In [6]:
# Verificando valores nan.

df_dados.isnull().sum()
# Agrupando e substituindo.

emprego = df_dados.groupby('Emprego').size()
emprego

df_dados['Emprego'] = df_dados['Emprego'].fillna('1<=X<4 ')
df_dados['Emprego'].isnull().sum()

profissao = df_dados.groupby('Profissao').size()
profissao

df_dados['Profissao'] = df_dados['Profissao'].fillna('qualificado')
df_dados['Profissao'].isnull().sum()

histcred = df_dados.groupby('Historico_Credito').size()
histcred

df_dados['Historico_Credito'] = df_dados['Historico_Credito'].fillna('existentes/pagos')
df_dados['Historico_Credito'].isnull().sum()

np.int64(0)

In [7]:
previsores = df_dados.iloc[:, 0:9].values
classe = df_dados.iloc[:,9].values

label = LabelEncoder()

previsores[:, 3] = label.fit_transform(previsores[:, 3])
previsores[:, 4] = label.fit_transform(previsores[:, 4])
previsores[:, 5] = label.fit_transform(previsores[:, 5])
previsores[:, 6] = label.fit_transform(previsores[:, 6])
previsores[:, 7] = label.fit_transform(previsores[:, 7])
previsores[:, 8] = label.fit_transform(previsores[:, 8])


previsores = previsores.astype('float32') 

# Se a sua 'classe' também veio de texto ou é objeto:
classe = label.fit_transform(classe).astype('float32')

In [8]:
# Dividindo a base de dados em treino e teste.

X_treino, X_teste, Y_treino, Y_teste = train_test_split(previsores, classe, test_size= 0.3, random_state=0)

In [9]:
# Criação do modelo neural com o comando Sequential.
modelo = Sequential()

# A definição da entrada é feita fora das camadas.
modelo.add(Input(shape = (9,)))

# Primeira camada oculta com 5 neurônios.
modelo.add(Dense(units = 5, activation= 'relu'))

# Segunda camada oculta
modelo.add(Dense(units = 4, activation='relu'))

# Terceira camada oculta / Função softmax por que temos um problema de classificação com mais de duas classes.
modelo.add(Dense(units=1, activation= 'sigmoid'))

In [10]:
# Visualização da estrutura da rede neural.

modelo.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 5)              │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 79 (316.00 B)

 Trainable params: 79 (316.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
# Configuração dos parâmetros da rede neural (adam = atualiza os pesos / loss = calcula o erro). 

modelo.compile(optimizer='adam', loss = 'binary_crossentropy',
               metrics = ['accuracy'])

# Treinamento dividindo a base de treinamento em uma porção de validação.
modelo.fit(X_treino, Y_treino, epochs = 1000, validation_data = (X_teste, Y_teste))

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.2957 - loss: 1002.5663 - val_accuracy: 0.3100 - val_loss: 898.3819
Epoch 2/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.2957 - loss: 699.3252 - val_accuracy: 0.3100 - val_loss: 584.1882
Epoch 3/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.2986 - loss: 414.0581 - val_accuracy: 0.3133 - val_loss: 285.2722
Epoch 4/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3786 - loss: 131.7400 - val_accuracy: 0.6133 - val_loss: 12.8675
Epoch 5/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7086 - loss: 18.8192 - val_accuracy: 0.6200 - val_loss: 10.0527
Epoch 6/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6714 - loss: 9.7806 - val_accuracy: 0.6667 - val_loss: 9.1676
Epoch 7/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6714 - loss: 8.9300 - val_accuracy: 0.6667 - val_loss: 8.9839
Epoch 8/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6800 - loss: 8.2222 - val_accuracy: 0.6467 - val_loss: 8.6535
Epoch 9/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6900 - loss: 7.7336 - val_accuracy: 0.6433 - val_loss: 8.5970
Epoch 10/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6814 - loss: 7.5547 - val_accuracy: 0.7000 - val_loss: 9.3032
Epoch 11/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6857 - loss: 7.4996 - val_accuracy: 0.6600 - val_loss: 8.0404
Epoch 12/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6943 - loss: 7.3856 - val_accuracy: 0.6433 - val_loss: 7.9167
Epoch 13/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6843 - loss: 7.0885 - val_accuracy: 0.6433 - val_loss: 7.6092
Epoch 14/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6743 - loss: 7.6972 - val_accuracy: 0.6400 - val_loss: 7.3632
Epoch 15/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7029 - loss: 6.7008 - val_accuracy: 0.6267 - val_loss: 8.1879
Epoch 16/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6714 - loss: 6.8095 - val_accuracy: 0.6300 - val_loss: 8.0366
Epoch 17/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6771 - loss: 6.2662 - val_accuracy: 0.6833 - val_loss: 7.2817
Epoch 18/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6871 - loss: 6.4693 - val_accuracy: 0.6267 - val_loss: 8.5149
Epoch 19/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6629 - loss: 6.4848 - val_accuracy: 0.6433 - val_loss: 6.2278
Epoch 20/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6843 - loss: 5.6460 - val_accuracy: 0.6467 - val_loss: 5.9543
Epoch 21/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6771 - loss: 6.1785 - val_accuracy: 0.6267 - val_loss: 6.2986
Epoch 22/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6871 - loss: 5.1571 - val_accuracy: 0.6533 - val_loss: 5.4500
Epoch 23/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6800 - loss: 4.8929 - val_accuracy: 0.6500 - val_loss: 5.1591
Epoch 24/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6871 - loss: 4.6388 - val_accuracy: 0.6233 - val_loss: 5.8770
Epoch 25/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6857 - loss: 4.5018 - val_accuracy: 0.6533 - val_loss: 4.5789
Epoch 26/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6843 - loss: 4.1938 - val_accuracy: 0.6367 - val_loss: 4.4650
Epoch 27/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6786 - loss: 3.8139 - val_accuracy: 0.6800 - val_loss: 4.2125
Epoch 28/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6786 - loss: 3.7481 - val_accuracy: 0.6300 - val_loss: 3.6318
Epoch 29/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6829 - loss: 3.4724 - val_accuracy: 0.6433 - val_loss: 3.3863
Epoch 30/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6914 - loss: 3.1962 - val_accuracy: 0.6233 - val_loss: 3.3565
Epoch 31/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6614 - loss: 2.9516 - val_accuracy: 0.6233 - val_loss: 3.0120
Epoch 32/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6714 - loss: 2.8429 - val_accuracy: 0.6933 - val_loss: 3.0295
Epoch 33/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6771 - loss: 2.6852 - val_accuracy: 0.6500 - val_loss: 2.6149
Epoch 34/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6486 - loss: 3.2949 - val_accuracy: 0.5400 - val_loss: 4.4567
Epoch 35/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6771 - loss: 2.5047 - val_accuracy: 0.7000 - val_loss: 2.9183
Epoch 36/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6371 - loss: 2.7238 - val_accuracy: 0.6133 - val_loss: 2.3019
Epoch 37/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6386 - loss: 2.6417 - val_accuracy: 0.7000 - val_loss: 4.9215
Epoch 38/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6271 - loss: 2.9099 - val_accuracy: 0.5667 - val_loss: 2.5077
Epoch 39/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6514 - loss: 2.1825 - val_accuracy: 0.6800 - val_loss: 2.4721
Epoch 40/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6471 - loss: 2.6330 - val_accuracy: 0.5600 - val_loss: 2.4955
Epoch 41/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6414 - loss: 2.0148 - val_accuracy: 0.5600 - val_loss: 2.5916
Epoch 42/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6329 - loss: 3.5040 - val_accuracy: 0.7033 - val_loss: 4.7555
Epoch 43/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6257 - loss: 3.9928 - val_accuracy: 0.7033 - val_loss: 4.8039
Epoch 44/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6271 - loss: 3.2776 - val_accuracy: 0.5067 - val_loss: 3.6056
Epoch 45/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6200 - loss: 2.7739 - val_accuracy: 0.6667 - val_loss: 2.3649
Epoch 46/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6357 - loss: 2.1549 - val_accuracy: 0.6100 - val_loss: 1.9294
Epoch 47/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6343 - loss: 2.3775 - val_accuracy: 0.5700 - val_loss: 2.1332
Epoch 48/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6500 - loss: 2.1349 - val_accuracy: 0.5100 - val_loss: 3.2287
Epoch 49/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6514 - loss: 2.6148 - val_accuracy: 0.6033 - val_loss: 1.8219
Epoch 50/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6300 - loss: 3.3686 - val_accuracy: 0.4667 - val_loss: 4.7556
Epoch 51/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5971 - loss: 2.6766 - val_accuracy: 0.5533 - val_loss: 2.1102
Epoch 52/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6414 - loss: 1.6742 - val_accuracy: 0.5667 - val_loss: 1.8291
Epoch 53/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6486 - loss: 1.7231 - val_accuracy: 0.6100 - val_loss: 1.6916
Epoch 54/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5986 - loss: 2.4247 - val_accuracy: 0.5500 - val_loss: 1.9803
Epoch 55/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6157 - loss: 1.9723 - val_accuracy: 0.6967 - val_loss: 2.9850
Epoch 56/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6443 - loss: 3.0815 - val_accuracy: 0.6800 - val_loss: 2.1914
Epoch 57/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6214 - loss: 2.2800 - val_accuracy: 0.6967 - val_loss: 2.8388
Epoch 58/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6286 - loss: 2.1812 - val_accuracy: 0.5767 - val_loss: 1.6909
Epoch 59/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6257 - loss: 2.5925 - val_accuracy: 0.4433 - val_loss: 5.0422
Epoch 60/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6086 - loss: 2.8545 - val_accuracy: 0.6633 - val_loss: 1.5944
Epoch 61/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6257 - loss: 2.6870 - val_accuracy: 0.4967 - val_loss: 2.6709
Epoch 62/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6343 - loss: 1.9186 - val_accuracy: 0.5167 - val_loss: 2.5153
Epoch 63/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6114 - loss: 1.6131 - val_accuracy: 0.7000 - val_loss: 2.4787
Epoch 64/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6486 - loss: 2.2031 - val_accuracy: 0.4700 - val_loss: 3.6622
Epoch 65/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6357 - loss: 1.7938 - val_accuracy: 0.5767 - val_loss: 1.4461
Epoch 66/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6457 - loss: 1.7223 - val_accuracy: 0.5567 - val_loss: 1.6037
Epoch 67/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6486 - loss: 1.6353 - val_accuracy: 0.5333 - val_loss: 1.8653
Epoch 68/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6557 - loss: 1.3722 - val_accuracy: 0.6700 - val_loss: 1.5790
Epoch 69/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6300 - loss: 1.3130 - val_accuracy: 0.6733 - val_loss: 1.4980
Epoch 70/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6000 - loss: 2.9125 - val_accuracy: 0.3700 - val_loss: 6.3009
Epoch 71/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5957 - loss: 3.4139 - val_accuracy: 0.5767 - val_loss: 1.3019
Epoch 72/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6186 - loss: 1.7965 - val_accuracy: 0.6633 - val_loss: 1.2965
Epoch 73/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6486 - loss: 1.4188 - val_accuracy: 0.5333 - val_loss: 1.5607
Epoch 74/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6300 - loss: 1.9462 - val_accuracy: 0.6967 - val_loss: 3.1048
Epoch 75/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6357 - loss: 1.4927 - val_accuracy: 0.6933 - val_loss: 2.1880
Epoch 76/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6486 - loss: 1.6068 - val_accuracy: 0.4867 - val_loss: 2.4329
Epoch 77/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6443 - loss: 1.5444 - val_accuracy: 0.5167 - val_loss: 1.9628
Epoch 78/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6557 - loss: 1.5503 - val_accuracy: 0.6700 - val_loss: 1.2700
Epoch 79/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6271 - loss: 1.7054 - val_accuracy: 0.6933 - val_loss: 1.9715
Epoch 80/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6357 - loss: 2.1491 - val_accuracy: 0.6400 - val_loss: 1.0547
Epoch 81/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6414 - loss: 1.3799 - val_accuracy: 0.4833 - val_loss: 2.2618
Epoch 82/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6343 - loss: 1.3042 - val_accuracy: 0.6667 - val_loss: 1.1425
Epoch 83/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6471 - loss: 2.1666 - val_accuracy: 0.6900 - val_loss: 3.7756
Epoch 84/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6071 - loss: 2.9984 - val_accuracy: 0.5600 - val_loss: 1.3032
Epoch 85/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6171 - loss: 1.9943 - val_accuracy: 0.7000 - val_loss: 2.2962
Epoch 86/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6700 - loss: 1.3529 - val_accuracy: 0.6700 - val_loss: 0.9998
Epoch 87/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6529 - loss: 1.0122 - val_accuracy: 0.5567 - val_loss: 1.3796
Epoch 88/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6457 - loss: 1.2301 - val_accuracy: 0.7067 - val_loss: 1.8783
Epoch 89/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6857 - loss: 1.0694 - val_accuracy: 0.6200 - val_loss: 0.9627
Epoch 90/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6343 - loss: 1.1956 - val_accuracy: 0.5067 - val_loss: 1.6300
Epoch 91/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6329 - loss: 1.0698 - val_accuracy: 0.4800 - val_loss: 2.0180
Epoch 92/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6771 - loss: 0.9874 - val_accuracy: 0.6667 - val_loss: 0.9447
Epoch 93/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6357 - loss: 1.4171 - val_accuracy: 0.5033 - val_loss: 1.6914
Epoch 94/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6414 - loss: 1.1952 - val_accuracy: 0.6767 - val_loss: 0.8492
Epoch 95/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6143 - loss: 2.2807 - val_accuracy: 0.4500 - val_loss: 2.4538
Epoch 96/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6429 - loss: 2.1459 - val_accuracy: 0.4500 - val_loss: 2.6799
Epoch 97/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6557 - loss: 1.5595 - val_accuracy: 0.5900 - val_loss: 1.1267
Epoch 98/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6743 - loss: 1.0402 - val_accuracy: 0.5800 - val_loss: 1.0891
Epoch 99/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6800 - loss: 1.0993 - val_accuracy: 0.6733 - val_loss: 0.8373
Epoch 100/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6371 - loss: 1.4911 - val_accuracy: 0.5833 - val_loss: 1.2034
Epoch 101/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6443 - loss: 1.6007 - val_accuracy: 0.4767 - val_loss: 1.8890
Epoch 102/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6557 - loss: 1.4483 - val_accuracy: 0.6900 - val_loss: 3.6265
Epoch 103/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6214 - loss: 2.3343 - val_accuracy: 0.5267 - val_loss: 3.8601
Epoch 104/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6529 - loss: 2.8184 - val_accuracy: 0.6567 - val_loss: 0.9400
Epoch 105/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6486 - loss: 1.6002 - val_accuracy: 0.6967 - val_loss: 0.9545
Epoch 106/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7143 - loss: 0.8443 - val_accuracy: 0.6567 - val_loss: 0.7984
Epoch 107/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6643 - loss: 1.0202 - val_accuracy: 0.7000 - val_loss: 1.0555
Epoch 108/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6700 - loss: 0.9898 - val_accuracy: 0.5667 - val_loss: 0.9418
Epoch 109/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6571 - loss: 0.9314 - val_accuracy: 0.6567 - val_loss: 0.7419
Epoch 110/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6743 - loss: 0.8829 - val_accuracy: 0.6700 - val_loss: 0.7171
Epoch 111/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6600 - loss: 1.1744 - val_accuracy: 0.7000 - val_loss: 1.1740
Epoch 112/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6271 - loss: 1.5384 - val_accuracy: 0.4433 - val_loss: 2.1117
Epoch 113/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6600 - loss: 1.2186 - val_accuracy: 0.5433 - val_loss: 1.1163
Epoch 114/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6729 - loss: 0.7587 - val_accuracy: 0.6700 - val_loss: 0.7128
Epoch 115/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6714 - loss: 0.9862 - val_accuracy: 0.7000 - val_loss: 1.0670
Epoch 116/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6314 - loss: 2.2155 - val_accuracy: 0.6900 - val_loss: 4.9024
Epoch 117/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6614 - loss: 1.7926 - val_accuracy: 0.6933 - val_loss: 0.7961
Epoch 118/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6643 - loss: 0.9641 - val_accuracy: 0.6733 - val_loss: 0.7042
Epoch 119/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6657 - loss: 0.8075 - val_accuracy: 0.5867 - val_loss: 0.8945
Epoch 120/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6871 - loss: 0.8256 - val_accuracy: 0.7033 - val_loss: 0.9877
Epoch 121/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6514 - loss: 1.0321 - val_accuracy: 0.6967 - val_loss: 1.7659
Epoch 122/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6614 - loss: 1.1730 - val_accuracy: 0.7000 - val_loss: 1.5375
Epoch 123/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6543 - loss: 1.1803 - val_accuracy: 0.4033 - val_loss: 2.0044
Epoch 124/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6471 - loss: 1.0008 - val_accuracy: 0.6933 - val_loss: 0.9565
Epoch 125/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6914 - loss: 0.7009 - val_accuracy: 0.5433 - val_loss: 1.0665
Epoch 126/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6357 - loss: 1.7195 - val_accuracy: 0.4433 - val_loss: 1.6779
Epoch 127/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5929 - loss: 3.1275 - val_accuracy: 0.3500 - val_loss: 3.8346
Epoch 128/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6271 - loss: 2.1591 - val_accuracy: 0.4333 - val_loss: 2.0489
Epoch 129/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6329 - loss: 1.7858 - val_accuracy: 0.3433 - val_loss: 4.0960
Epoch 130/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6057 - loss: 1.8366 - val_accuracy: 0.6867 - val_loss: 0.6839
Epoch 131/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7057 - loss: 0.8495 - val_accuracy: 0.5533 - val_loss: 1.1063
Epoch 132/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6343 - loss: 1.5745 - val_accuracy: 0.3900 - val_loss: 2.4531
Epoch 133/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6100 - loss: 1.7777 - val_accuracy: 0.4367 - val_loss: 2.0116
Epoch 134/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6243 - loss: 1.7238 - val_accuracy: 0.6900 - val_loss: 1.1136
Epoch 135/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6671 - loss: 1.1827 - val_accuracy: 0.6867 - val_loss: 0.6957
Epoch 136/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6857 - loss: 0.7753 - val_accuracy: 0.6267 - val_loss: 0.7656
Epoch 137/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6514 - loss: 1.0938 - val_accuracy: 0.6933 - val_loss: 0.9585
Epoch 138/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6471 - loss: 1.4012 - val_accuracy: 0.6100 - val_loss: 0.8708
Epoch 139/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6614 - loss: 0.9172 - val_accuracy: 0.5533 - val_loss: 1.0777
Epoch 140/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6643 - loss: 1.3719 - val_accuracy: 0.6133 - val_loss: 0.8353
Epoch 141/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7086 - loss: 0.6194 - val_accuracy: 0.6800 - val_loss: 0.6853
Epoch 142/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6657 - loss: 1.0524 - val_accuracy: 0.7100 - val_loss: 0.7532
Epoch 143/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6286 - loss: 1.2488 - val_accuracy: 0.5300 - val_loss: 1.4089
Epoch 144/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6286 - loss: 1.8795 - val_accuracy: 0.5500 - val_loss: 1.3147
Epoch 145/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6557 - loss: 1.0830 - val_accuracy: 0.5167 - val_loss: 1.5768
Epoch 146/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6200 - loss: 1.4501 - val_accuracy: 0.4200 - val_loss: 2.1768
Epoch 147/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7086 - loss: 0.7913 - val_accuracy: 0.6833 - val_loss: 0.6676
Epoch 148/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6957 - loss: 0.7389 - val_accuracy: 0.6867 - val_loss: 1.1530
Epoch 149/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6857 - loss: 0.9208 - val_accuracy: 0.3700 - val_loss: 2.8826
Epoch 150/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6171 - loss: 1.4172 - val_accuracy: 0.6933 - val_loss: 1.4744
Epoch 151/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6543 - loss: 1.2875 - val_accuracy: 0.6900 - val_loss: 1.5056
Epoch 152/1000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6343 - loss: 1.1459 - val_accuracy: 0.5600 - val_loss: 1.0682
Epoch 153/1000

In [12]:
previsoes = modelo.predict(X_teste)
previsoes = (previsoes > 0.5)
previsoes

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

array([[False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True]])

In [13]:
acerto = accuracy_score(Y_teste, previsoes)
acerto

0.7